Span hosts

diff --git a/miceweb b/miceweb
--- a/miceweb
+++ b/miceweb
@@ -859,6 +859,23 @@ _save_wget_ipns() {
 	fi
 	return 1
 }
+_save_wget_span() {
+	local DT=$(export TZ=GMT ; date '+%Y%m%dGMT%H%M%S')
+	SUBDIR="$DT-wget-span"
+	ipfs files ls /$SAVE_MFS_ADDR/$SUBDIR &>/dev/null
+	if [ $? -ne 0 ]; then
+		_wget $1
+		if [ $? -ne 0 ]; then
+			if [[ $1 != http://127.0.0.1* ]]; then
+				_wget $1 --torsocks
+			fi
+		fi
+		return $?
+	else
+		>&2 echo "$SUBDIR exists"
+		return 0
+	fi
+}
 _save_wget() {
 	local DT=$(export TZ=GMT ; date '+%Y%m%dGMT%H%M%S')
 	SUBDIR="$DT-wget"
@@ -1191,11 +1208,15 @@ _wget() {
 	echo "Log $RAND" > $MYTMPFILE
 	echo "$comment" >> $MYTMPFILE
 	local USERAGENT="Mozilla/5.0 (Windows NT 10.0; rv:91.0) Gecko/20100101 Firefox/91.0"
+	local span=""
+	if [[ $SUBDIR == *-span ]]; then
+		span="--span-hosts"
+	fi
 	if [ "$options" != "--torsocks" ]; then
-		wget --adjust-extension --no-cache --page-requisites --follow-ftp --restrict-file-names=windows --convert-links --backup-converted --no-host-directories --timeout=30 --tries=2 --user-agent="$USERAGENT" $options --append-output=$MYTMPFILE "$URL"
+		wget --adjust-extension --no-cache --page-requisites --follow-ftp --restrict-file-names=windows --convert-links --backup-converted --no-host-directories $span --timeout=30 --tries=1 --user-agent="$USERAGENT" $options --append-output=$MYTMPFILE "$URL"
 	else
 		if _command_exists torsocks; then
-			torsocks --isolate wget --adjust-extension --no-cache --page-requisites --follow-ftp --restrict-file-names=windows --convert-links --backup-converted --no-host-directories --timeout=30 --tries=1 --user-agent="$USERAGENT" --append-output=$MYTMPFILE "$URL" 2>/dev/null
+			torsocks --isolate wget --adjust-extension --no-cache --page-requisites --follow-ftp --restrict-file-names=windows --convert-links --backup-converted --no-host-directories $span --timeout=30 --tries=1 --user-agent="$USERAGENT" --append-output=$MYTMPFILE "$URL" 2>/dev/null
 		fi
 	fi
 	local WGETERR=$?
@@ -1211,7 +1232,10 @@ _wget() {
 		fi
 	else
 		if [ "$options" != "--torsocks" ]; then
-			>&2 echo "Error: wget can't download $1 (err. $WGETERR)"
+			if [ "$span" != "" ]; then
+				span=" $span"
+			fi
+			>&2 echo "Error: wget$span can't download $URL (err. $WGETERR)"
 		fi
 	fi
 	cd ..
@@ -1929,7 +1953,7 @@ save() {
 		for I in $("$0" "$@" 2>/dev/null)
 		do
 			if _check_url "$I"; then
-				local VERSIONS_COUNT=$(_versions "$(_url_but_fragment $I)" | grep -e "^.*-wget$" -e "^.*-wget-ip.s$" | wc -l)
+				local VERSIONS_COUNT=$(_versions "$(_url_but_fragment $I)" | grep -e "^.*-wget$" -e "^.*-wget-span$" -e "^.*-wget-ip.s$" | wc -l)
 				if [ "$VERSIONS_COUNT" -eq 0 ]; then
 					if ! _check_free_space_for_temp
 					then
@@ -2017,19 +2041,23 @@ save() {
 			elif [[ $URL == ipfs://* ]]; then
 				_save_wget_ipfs "${URL#ipfs://}"
 			else
-				_save_wget $URL
+				_save_wget_span $URL
 				if [ $? -ne 0 ]; then
-					if [[ $URL == http://127.0.0.1:43110/* ]]; then
-						if [[ $URL != http://127.0.0.1:43110/raw/* ]]; then
-							local ext=$(_parse_extension "$URL")
-							if [[ "$ext" == "" || $ext == htm || $ext == html ]]; then
-								_save_zeronet "${PARSEDPATH#/}"
-							fi
-						fi
-					else
+					if [[ $URL != http://127.0.0.1* ]]; then
 						_save_archived $URL
 					fi
-					_save_curl $URL
+					_save_wget $URL
+					if [ $? -ne 0 ]; then
+						if [[ $URL == http://127.0.0.1:43110/* ]]; then
+							if [[ $URL != http://127.0.0.1:43110/raw/* ]]; then
+								local ext=$(_parse_extension "$URL")
+								if [[ "$ext" == "" || $ext == htm || $ext == html ]]; then
+									_save_zeronet "${PARSEDPATH#/}"
+								fi
+							fi
+						fi
+						_save_curl $URL
+					fi
 				fi
 			fi
 			PARSEDPATH=$(_parse_path $URL)
