Fixed resolving zeronet domains Supported https://github.com/zeronet-conservancy/zeronet-conservancy/issues/23

diff --git a/miceweb b/miceweb
--- a/miceweb
+++ b/miceweb
@@ -821,16 +821,18 @@ _resolve_zeronet() {
 	local MAIN=$(echo "$1" | awk -F/ '{print $1}')
 	if [[ $MAIN == *.* ]]; then
 		local DOMAIN=$MAIN
-		MAIN=$(curl http://127.0.0.1:43110/raw/$MAIN/content.json 2>/dev/null | jq --raw-output '.address' 2>/dev/null)
+		MAIN=$(wget http://127.0.0.1:43110/raw/$MAIN/content.json --timeout=1 --output-document=- 2>/dev/null | jq --raw-output '.address' 2>/dev/null)
 		if [[ $MAIN == 1* ]]; then
 			echo $MAIN"${1#$DOMAIN}"
 			return 0
 		elif [[ $MAIN == "" ]]; then
 			>&2 echo "Error: running ZeroNet node is required to resolve such domains"
 			return 1
+		else
+			>&2 echo "Error: could not resolve /zeronet/$DOMAIN"
+			return 1
 		fi
-	fi
-	if [[ $MAIN == 1* ]]; then
+	elif [[ $MAIN == 1* ]]; then
 		echo $1
 		return 0
 	fi
@@ -1085,7 +1087,7 @@ _save_zite() {
 	local DOMAIN=$(echo "$1" | awk -F/ '{print $1}')
 	if [[ $DOMAIN == *.* ]]; then
 		MAIN=$(_resolve_zeronet $DOMAIN)
-		if [[ $MAIN != $DOMAIN ]]; then
+		if [[ $MAIN != $DOMAIN && "$MAIN" != "" ]]; then
 			>&2 echo "Resolved /zeronet/$DOMAIN to /zeronet/$MAIN"
 		fi
 	else
