v.0.2

diff --git a/miceweb b/miceweb
--- a/miceweb
+++ b/miceweb
@@ -160,7 +160,7 @@ _ME="$(basename "${0}")"
 #
 # Manually set this to to current version of the program. Adhere to the
 # semantic versioning specification: http://semver.org
-_VERSION="0.1"
+_VERSION="0.2"
 
 # $DEFAULT_SUBCOMMAND
 #
@@ -663,18 +663,18 @@ _subcommands() {
 
 # version #####################################################################
 
-#describe "version" <<HEREDOC
-#Usage:
-#  ${_ME} ( version | --version )
-#
-#Description:
-#  Display the current program version.
-#
-#  To save you the trouble, the current version is ${_VERSION}
-#HEREDOC
-#version() {
-#  printf "%s\\n" "${_VERSION}"
-#}
+describe "version" <<HEREDOC
+Usage:
+  ${_ME} ( version | --version )
+
+Description:
+  Display the current program version.
+
+  To save you the trouble, the current version is ${_VERSION}
+HEREDOC
+version() {
+  printf "%s\\n" "${_VERSION}"
+}
 
 ###############################################################################
 # Subcommands
@@ -933,7 +933,30 @@ hash() {
 		>&2 echo "This subcommand requires URL as a parameter"
 		return 1
 	fi
-	HASH="$(echo $1 | ipfs add --only-hash --quieter --cid-version=0)"
+	local HASH=$(echo -n "$1" | sha1sum 2>/dev/null | cut -d' ' -f1)
+	if [[ "$HASH" != "" ]]; then
+		echo "$HASH"
+	else
+		HASH=$(echo -n "$1" | openssl sha1 -r 2>/dev/null | cut -d' ' -f1)
+		if [[ "$HASH" != "" ]]; then
+			echo "$HASH"
+		else
+			HASH=$(echo -n "$1" | shasum -a 1 2>/dev/null | cut -d' ' -f1)
+			if [[ "$HASH" != "" ]]; then
+				echo "$HASH"
+			else
+				_exit_1 printf "Installed sha1sum, shasum or openssl is required for MiceWeb\n"
+			fi
+		fi
+	fi
+}
+
+_old_hashhash() {
+	if [[ "$1" == "" ]]; then
+		>&2 echo "This subcommand requires URL as a parameter"
+		return 1
+	fi
+	local HASH="$(echo $1 | ipfs add --only-hash --quieter --cid-version=0)"
 	if [[ "$HASH" != "" ]]; then
 		HASH="page-$HASH"
 		echo "$HASH"
@@ -967,6 +990,7 @@ Description:
   Save web page by URL
 HEREDOC
 save() {
+	_upgrade
 	#TODO: --archives={default|none|last|all}, --tor={default|yes|no}
 	if [[ "$1" == "urls" ]]; then
 		_reprovidingWarning
@@ -991,6 +1015,18 @@ save() {
 		done
 		>&2 echo "Done"
 		return 0
+	fi
+	if [[ "$1" == "url" ]]; then
+		if [[ "$2" != "" ]]; then
+			URL=$(url "$2")
+			if [[ "$URL" != "" ]]; then
+				save $URL
+				return $?
+			fi
+		else
+			url
+		fi
+		return 1
 	fi
 	URL=""
 	local _arguments=()
@@ -1070,6 +1106,40 @@ save() {
 	fi
 }
 
+describe "url" <<HEREDOC
+Usage:
+  ${_ME} url <file>
+
+Description:
+  Return URL by SHA-1 hash
+HEREDOC
+url() {
+	_upgrade
+	if [[ "$1" == "" ]]; then
+		>&2 echo "This subcommand requires SHA-1 hash as a parameter"
+		return 1
+	fi
+	local CACHE_FILE="$HOME/.miceweb/cache/urls/$1"
+	local URL=$(grep "" "$CACHE_FILE" 2>/dev/null)
+	if [[ "$URL" != "" ]]; then
+		local HASH=$(hash "$URL")
+		if [[ "$1" == "$HASH" ]]; then
+			echo "$URL"
+			return 0
+		fi
+	fi
+	URL=$(ipfs files read /MiceWeb/pages/$1/URL.txt | sed -n 2p)
+	if [[ "$URL" != "" ]]; then
+		local HASH=$(hash "$URL")
+		if [[ "$1" == "$HASH" ]]; then
+			echo "$URL" > "$CACHE_FILE"
+			echo "$URL"
+			return 0
+		fi
+	fi
+	return 1
+}
+
 describe "urls" <<HEREDOC
 Usage:
   ${_ME} urls <file>
@@ -1078,6 +1148,7 @@ Description:
   List URLs from file (text or json)
 HEREDOC
 urls() {
+	_upgrade
 	FIL=""
 	PARAM=""
 	GREP=""
@@ -1107,12 +1178,13 @@ urls() {
 		CID="$(ipfs files stat --hash /MiceWeb/pages/)"
 		if [[ "$CID" != "" ]]; then
 			>&2 echo "There are URLs already in the MiceWeb Library (see also 'miceweb history'):"
-			mkdir --parents "$HOME/.miceweb/cache/urls"
-			for I in $(ipfs files ls /MiceWeb/pages/); do
-				if [[ $I == page-* ]]; then
+			local CACHE_DIR="$HOME/.miceweb/cache/urls/"
+			mkdir --parents "$CACHE_DIR"
+			for I in $(ipfs files ls /MiceWeb/pages/ | grep ^[0-9a-f]); do
+				#if [[ $I == page-* ]]; then
 					#MD5=`echo "$I" | md5sum | awk '{ print $1 }'`
-					CACHE_FILE="$HOME/.miceweb/cache/urls/$I-URL"
-					URL=$(grep "" "$CACHE_FILE" 2>/dev/null)
+					local CACHE_FILE="$CACHE_DIR$I"
+					local URL=$(grep "" "$CACHE_FILE" 2>/dev/null)
 					if [[ "$URL" != "" ]]; then
 						echo "$URL" | grep "$GREP"
 					else
@@ -1124,7 +1196,7 @@ urls() {
 							>&2 echo "Error: $I not resolved"
 						fi
 					fi
-				fi
+				#fi
 			done
 			>&2 echo ""
 		fi
@@ -1175,6 +1247,7 @@ Description:
   Remove all saved versions of web page by URL
 HEREDOC
 remove() {
+	_upgrade
 	URL="$1"
 	if [[ "$URL" == "" ]]; then
 		>&2 echo "This subcommand requires URL as a parameter"
@@ -1182,9 +1255,16 @@ remove() {
 	fi
 	HASH=$(hash "$URL")
 	if [[ "$HASH" != "" ]]; then
-		MFS_ADDR="/MiceWeb/pages/$HASH"
-		ipfs files rm -r $MFS_ADDR
-		return $?
+		PRESENT=$(present "$URL" 2>/dev/null)
+		if [[ "$PRESENT" != "" ]]; then
+			MFS_ADDR="/MiceWeb/pages/$HASH"
+			ipfs files rm -r $MFS_ADDR
+			>&2 echo "Removed $URL from the MiceWeb Library"
+			>&2 echo ""
+			>&2 echo "You can try to undo that right now by running"
+			>&2 echo " 'ipfs files cp $PRESENT $MFS_ADDR'"
+			return $?
+		fi
 	else
 		return 1	
 	fi
@@ -1214,6 +1294,50 @@ _versions() {
 	fi
 }
 
+_upgrade() {
+	TESTHASH1=$(hash "test")
+	if [[ "$TESTHASH1" != "a94a8fe5ccb19ba61c4c0873d391e987982fbbd3" ]]; then
+		exit 1
+	fi
+	VERTXT="/MiceWeb/attributes.txt"
+	VER=$(ipfs files read $VERTXT 2>/dev/null | sed -n 2p)
+	if [[ $VER == "" ]]; then
+		local TESTHASH2="$(echo -n "test" | ipfs add --only-hash --quieter --cid-version=0)"
+		if [[ "$TESTHASH2" != "QmRf22bZar3WKmojipms22PkXH1MZGmvsqzQtuSvQE3uhm" ]]; then
+			_exit_1 printf "Installed https://github.com/ipfs/go-ipfs is required for MiceWeb\n"
+		fi
+	fi
+	local APPVER="v.${_VERSION}"
+	if [[ $APPVER != $VER ]]; then
+		if [[ $VER == "" ]]; then
+			ipfs files mkdir /MiceWeb 2>/dev/null
+			ipfs files mkdir /MiceWeb/pages 2>/dev/null
+			CID="$(ipfs files stat --hash /MiceWeb/pages/)"
+			if [[ "$CID" != "" ]]; then
+				for I in $(ipfs files ls /MiceWeb/pages/ | grep ^page-Qm); do
+					URL=$(ipfs cat /ipfs/$CID/$I/URL.txt 2>/dev/null | sed -n 2p)
+					if [[ "$URL" != "" ]]; then
+						>&2 echo -n "Upgrading $URL..."
+						HASH=$(hash "$URL")
+						>&2 echo -n "."
+						if [[ "$HASH" != "" ]]; then
+							ipfs files mv /MiceWeb/pages/$I "/MiceWeb/pages/$HASH"
+						fi
+						>&2 echo "."
+					fi
+				done
+				VERTXTCID="$(printf "%s\n%s\n" "Library $(_random_value)" "$APPVER" | ipfs add --quieter --pin=false)"
+				ipfs files cp /ipfs/$VERTXTCID $VERTXT
+				if [ $? -eq 0 ]; then
+					return 0
+				fi
+			fi
+			_exit_1 printf "Can't upgrade the MiceWeb Library\n"
+		fi
+	fi
+	return 0
+}
+
 describe "present" <<HEREDOC
 Usage:
   ${_ME} present [<URL>]
@@ -1222,6 +1346,7 @@ Description:
   Present saved versions of web page by URL
 HEREDOC
 present() {
+	_upgrade
 	if [[ "$1" == "urls" ]]; then
 		if [[ "$2" != "" ]]; then
 			ipfs files mkdir /MiceWeb 2>/dev/null
@@ -1259,6 +1384,22 @@ present() {
 		>&2 echo "Run 'miceweb save ${@@Q}'"
 		return 1
 	fi
+	if [[ "$1" == "url" ]]; then
+		if [[ "$2" != "" ]]; then
+			URL=$(url "$2")
+			if [[ "$URL" != "" ]]; then
+				present $URL
+				if [ $? -eq 0 ]; then
+					return 0
+				#else
+					#>&2 echo "Run 'miceweb save ""$URL""'"
+				fi
+			fi
+		else
+			url
+		fi
+		return 1
+	fi
 	URL="$1"
 	HASH=$(hash "$URL" 2>/dev/null)
 	MFS_ADDR="/MiceWeb/pages/$HASH"
@@ -1288,17 +1429,18 @@ present() {
 		fi
 		echo "/ipfs/$CID"
 		>&2 echo ""
-		STAT=""
-		COUNT=0
+		local STAT=""
+		local COUNT=0
 		if [[ $HASH != */* ]]; then
-			for I in $(ipfs files ls /MiceWeb/pages/$HASH); do
-				if [[ $I != *.* ]]; then
-					((COUNT++))
-				fi
-			done
 			if [[ "$HASH" == "" ]]; then
+				COUNT=$(ipfs files ls /MiceWeb/pages | grep ^[0-9a-f] | wc -l)
 				STAT=$", NumURLs: $COUNT"
 			else
+				for I in $(ipfs files ls /MiceWeb/pages/$HASH); do
+					if [[ $I != *.* ]]; then
+						((COUNT++))
+					fi
+				done
 				STAT=$", NumVersions: $COUNT"
 			fi
 		fi
