Improved downloading (deprecated -wget-span)

diff --git a/miceweb b/miceweb
--- a/miceweb
+++ b/miceweb
@@ -871,25 +871,6 @@ _save_wget_ipns() {
 	fi
 	return 1
 }
-_save_wget_span() {
-	local DT=$(export TZ=GMT ; date '+%Y%m%dGMT%H%M%S')
-	SUBDIR="$DT-wget-span"
-	ipfs files ls /$SAVE_MFS_ADDR/$SUBDIR &>/dev/null
-	if [ $? -ne 0 ]; then
-		_wget $1
-		if [ $? -ne 0 ]; then
-			if [[ $1 != http://127.0.0.1* ]]; then
-				_wget $1 --torsocks
-			else
-				return 1
-			fi
-		fi
-		return $?
-	else
-		>&2 echo "$SUBDIR exists"
-		return 0
-	fi
-}
 _save_wget() {
 	local DT=$(export TZ=GMT ; date '+%Y%m%dGMT%H%M%S')
 	SUBDIR="$DT-wget"
@@ -1224,10 +1205,7 @@ _wget() {
 	echo "Log $RAND" > $MYTMPFILE
 	echo "$comment" >> $MYTMPFILE
 	local USERAGENT="Mozilla/5.0 (Windows NT 10.0; rv:91.0) Gecko/20100101 Firefox/91.0"
-	local span=""
-	if [[ $SUBDIR == *-span ]]; then
-		span="--span-hosts"
-	fi
+	local span="--span-hosts"
 	local robotsoff="--execute=robots=off"
 	if [ "$options" != "--torsocks" ]; then
 		wget --adjust-extension --no-cache --page-requisites --follow-ftp --no-remove-listing --retr-symlinks --restrict-file-names=windows --convert-links --backup-converted --no-host-directories $span $robotsoff --timeout=30 --tries=1 --user-agent="$USERAGENT" $options --append-output=$MYTMPFILE "$URL"
@@ -1238,7 +1216,11 @@ _wget() {
 	fi
 	local WGETERR=$?
 	local RET=1
-	if [[ $WGETERR -eq 0 || $WGETERR -eq 8 ]] && [ $(ls -A "$MYTMPDIR" | wc -l) -ne 0 ]; then
+	#TODO: what about err. 6 (username/password authentication failure)?
+	if [[ $WGETERR -eq 0 || $WGETERR -eq 4 || $WGETERR -eq 5 || $WGETERR -eq 7 || $WGETERR -eq 8 ]] && [ $(ls -A "$MYTMPDIR" | wc -l) -ne 0 ]; then
+		if [ $WGETERR -ne 0 ]; then
+			>&2 echo "Warning: detected issues when downloading, wget err. $WGETERR"
+		fi
 		local CID="$(ipfs add --quieter --pin=false -r $MYTMPDIR)"
 		ipfs files cp //ipfs/$CID /$SAVE_MFS_ADDR/$SUBDIR
 		if [ $? -eq 0 ]; then
@@ -1249,7 +1231,7 @@ _wget() {
 		fi
 	else
 		if [ "$options" != "--torsocks" ]; then
-			>&2 echo "Error: could not download ${SUBDIR:17}, err. $WGETERR"
+			>&2 echo "Error: could not download ${SUBDIR:17}, wget err. $WGETERR"
 		fi
 	fi
 	cd ..
@@ -2072,24 +2054,21 @@ save() {
 			elif [[ $URL == ipfs://* ]]; then
 				_save_wget_ipfs "${URL#ipfs://}"
 			else
-				_save_wget_span $URL
+				_save_wget $URL
 				if [ $? -ne 0 ]; then
-					_save_wget $URL
-					if [ $? -ne 0 ]; then
-						if [[ $URL == http://127.0.0.1:43110/* ]]; then
-							if [[ $URL != http://127.0.0.1:43110/raw/* ]]; then
-								local ext=$(_parse_extension "$URL")
-								if [[ "$ext" == "" || $ext == htm || $ext == html ]]; then
-									_save_zeronet "${PARSEDPATH#/}"
-								fi
+					if [[ $URL == http://127.0.0.1:43110/* ]]; then
+						if [[ $URL != http://127.0.0.1:43110/raw/* ]]; then
+							local ext=$(_parse_extension "$URL")
+							if [[ "$ext" == "" || $ext == htm || $ext == html ]]; then
+								_save_zeronet "${PARSEDPATH#/}"
 							fi
 						fi
-						_save_curl $URL
 					fi
-					if [[ $URL == http*://* ]]; then
-						if [[ $URL != http://127.0.0.1* ]]; then
-							_save_archived $URL
-						fi
+					_save_curl $URL
+				fi
+				if [[ $URL == http*://* ]]; then
+					if [[ $URL != http://127.0.0.1* ]]; then
+						_save_archived $URL
 					fi
 				fi
 			fi
